/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2020-06-11T13:58:24.386-04:00
  3.30.0.4
  
  Standalone prediction code with sample test data for XGBoostModel named xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://192.168.1.200:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://192.168.1.200:54321/3/Models.java/xgboost-02091d16-b8d0-4cb5-b069-5155cb9f126f > xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f.java
      javac8 -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;

@ModelPojo(name="xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f", algorithm="xgboost")
public class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f extends GenModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Multinomial; }

  public boolean isSupervised() { return true; }
  public int nclasses() { return 3; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f.VALUES;
  // Number of output classes included in training data response column.
  public static final int NCLASSES = 3;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* sepal_length */ null,
    /* sepal_width */ null,
    /* petal_length */ null,
    /* petal_width */ null,
    /* species */ xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_ColInfo_4.VALUES
  };
  // Prior class distribution
  public static final double[] PRIOR_CLASS_DISTRIB = {0.3333333333333333,0.3333333333333333,0.3333333333333333};
  // Class distribution used for model building
  public static final double[] MODEL_CLASS_DISTRIB = null;

  public xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f() { super(NAMES,DOMAINS,"species"); }
  public String getUUID() { return Long.toString(2426931623574624598L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    float preds_0 = 0f;
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_0.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_1.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_2.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_3.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_4.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_5.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_6.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_7.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_8.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_9.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_10.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_11.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_12.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_13.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_14.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_15.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_16.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_17.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_18.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_19.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_20.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_21.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_22.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_23.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_24.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_25.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_26.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_27.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_28.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_29.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_30.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_31.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_32.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_33.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_34.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_35.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_36.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_37.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_38.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_39.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_40.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_41.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_42.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_43.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_44.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_45.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_46.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_47.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_48.score0(data);
    preds_0 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_49.score0(data);
    preds_0 += 0.5f;
    preds[0] = preds_0;
    float preds_1 = 0f;
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_0.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_1.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_2.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_3.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_4.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_5.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_6.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_7.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_8.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_9.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_10.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_11.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_12.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_13.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_14.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_15.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_16.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_17.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_18.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_19.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_20.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_21.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_22.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_23.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_24.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_25.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_26.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_27.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_28.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_29.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_30.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_31.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_32.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_33.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_34.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_35.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_36.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_37.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_38.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_39.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_40.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_41.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_42.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_43.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_44.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_45.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_46.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_47.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_48.score0(data);
    preds_1 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_49.score0(data);
    preds_1 += 0.5f;
    preds[1] = preds_1;
    float preds_2 = 0f;
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_0.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_1.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_2.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_3.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_4.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_5.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_6.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_7.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_8.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_9.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_10.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_11.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_12.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_13.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_14.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_15.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_16.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_17.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_18.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_19.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_20.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_21.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_22.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_23.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_24.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_25.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_26.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_27.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_28.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_29.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_30.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_31.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_32.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_33.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_34.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_35.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_36.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_37.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_38.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_39.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_40.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_41.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_42.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_43.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_44.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_45.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_46.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_47.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_48.score0(data);
    preds_2 += xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_49.score0(data);
    preds_2 += 0.5f;
    preds[2] = preds_2;
    double max = preds[0];
    for (int i = 1; i < preds.length-1; i++) max = Math.max(preds[i], max);
    double sum = 0.0D;
    for (int i = 0; i < preds.length-1; i++) {
      preds[i] = Math.exp(preds[i] - max);
      sum += preds[i];
    }
    for (int i = 0; i < preds.length-1; i++) {
      preds[i] /= (float) sum;
    }
    for (int i = preds.length-2; i >= 0; i--)
      preds[1 + i] = preds[i];
    preds[0] = GenModel.getPrediction(preds, PRIOR_CLASS_DISTRIB, data, 0.5);
    return preds;
  }
}
// The class representing training column names
class NamesHolder_xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f implements java.io.Serializable {
  public static final String[] VALUES = new String[4];
  static {
    NamesHolder_xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_0.fill(VALUES);
  }
  static final class NamesHolder_xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "sepal_length";
      sa[1] = "sepal_width";
      sa[2] = "petal_length";
      sa[3] = "petal_width";
    }
  }
}
// The class representing column species
class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_ColInfo_4 implements java.io.Serializable {
  public static final String[] VALUES = new String[3];
  static {
    xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_ColInfo_4_0.fill(VALUES);
  }
  static final class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_ColInfo_4_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "0";
      sa[1] = "1";
      sa[2] = "2";
    }
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_0 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
        -0.21989927f
        :
        0.21724138f
      )
      :
      0.40298507f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_1 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
        -0.1958218f
        :
        -0.002693671f
      )
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
          -0.10741262f
          :
          ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
            0.20987163f
            :
            -0.026571559f
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
          0.0771064f
          :
          0.29754013f
        )
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_2 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
        -0.18016554f
        :
        0.0072648847f
      )
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
          -0.057822764f
          :
          0.12233818f
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
          0.06301815f
          :
          0.2372044f
        )
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_3 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
        -0.1691042f
        :
        0.013757921f
      )
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
          -0.045259736f
          :
          0.10035609f
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
          0.05190547f
          :
          0.20394923f
        )
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_4 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
        -0.16050857f
        :
        0.012577154f
      )
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
          -0.038876045f
          :
          0.0858836f
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
          0.042941872f
          :
          0.18301705f
        )
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_5 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
        -0.15349096f
        :
        0.013445123f
      )
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
          0.07175103f
          :
          -0.041498013f
        )
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
            -0.028885141f
            :
            0.09778843f
          )
          :
          0.1739877f
        )
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_6 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
        -0.14734577f
        :
        0.014260324f
      )
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 5.1499996f) ?
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
          -0.041549716f
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
            0.035180263f
            :
            0.13852356f
          )
        )
        :
        0.16317268f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_7 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
        -0.14155465f
        :
        0.014986594f
      )
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 5.1499996f) ?
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
          -0.038381748f
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
            0.024111496f
            :
            0.12822624f
          )
        )
        :
        0.1535347f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_8 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
        -0.1392972f
        :
        0.053288314f
      )
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
          0.0847027f
          :
          -0.052510962f
        )
        :
        0.14296323f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_9 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
        -0.13322924f
        :
        0.03986048f
      )
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
          0.077819124f
          :
          -0.05211603f
        )
        :
        0.13626397f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_10 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
        -0.1270855f
        :
        0.033597358f
      )
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
          0.074260615f
          :
          -0.047729027f
        )
        :
        0.12931728f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_11 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
        -0.12043397f
        :
        0.028456239f
      )
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
          0.06971582f
          :
          -0.046801213f
        )
        :
        0.12249651f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_12 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 5.1499996f) ?
      ((Double.isNaN(data[1]) || ((float)data[1]) < 3.05f) ?
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
            -0.09156811f
            :
            0.008621005f
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
            0.110005915f
            :
            0.024345754f
          )
        )
        :
        -0.120479f
      )
      :
      0.12131728f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_13 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 5.1499996f) ?
      ((Double.isNaN(data[1]) || ((float)data[1]) < 3.05f) ?
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
            0.049705062f
            :
            -0.090026304f
          )
          :
          0.10066672f
        )
        :
        -0.11203215f
      )
      :
      0.11274994f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_14 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
      ((Double.isNaN(data[1]) || ((float)data[1]) < 3.05f) ?
        0.012866677f
        :
        -0.12171358f
      )
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
          0.070183f
          :
          -0.053318065f
        )
        :
        0.10486937f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_15 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
      ((Double.isNaN(data[1]) || ((float)data[1]) < 3.05f) ?
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6f) ?
          -0.08010732f
          :
          0.10033613f
        )
        :
        -0.117334045f
      )
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 5.1499996f) ?
        0.018276447f
        :
        0.09904708f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_16 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
      ((Double.isNaN(data[1]) || ((float)data[1]) < 3.05f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
          -0.006024235f
          :
          0.02695482f
        )
        :
        -0.11151415f
      )
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 5.1499996f) ?
        0.018479496f
        :
        0.09157548f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_17 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
        -0.09351066f
        :
        0.026505338f
      )
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
        0.012510595f
        :
        0.08386284f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_18 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 5.1499996f) ?
      ((Double.isNaN(data[1]) || ((float)data[1]) < 3.05f) ?
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
          -0.03629372f
          :
          0.06296152f
        )
        :
        -0.08474557f
      )
      :
      0.080440536f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_19 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
        -0.08533336f
        :
        0.026438652f
      )
      :
      ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
        0.0041258284f
        :
        0.056749288f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_20 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[1]) || ((float)data[1]) < 3.15f) ?
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
        ((Double.isNaN(data[1]) || ((float)data[1]) < 2.65f) ?
          0.03857857f
          :
          -0.049754202f
        )
        :
        0.09066121f
      )
      :
      -0.059370432f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_21 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
      -0.037728004f
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
        0.0020530247f
        :
        0.05186618f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_22 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[1]) || ((float)data[1]) < 3.05f) ?
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
        ((Double.isNaN(data[1]) || ((float)data[1]) < 2.65f) ?
          0.03586531f
          :
          -0.04525602f
        )
        :
        0.08510982f
      )
      :
      -0.050681084f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_23 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
        -0.078099236f
        :
        0.020425916f
      )
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
        0.0063254493f
        :
        0.051329743f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_24 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
      -0.04210628f
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
          0.038653996f
          :
          -0.05802728f
        )
        :
        0.08313822f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_25 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[1]) || ((float)data[1]) < 3.05f) ?
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
        -0.006374484f
        :
        0.054439146f
      )
      :
      -0.048055742f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_26 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
      -0.039388563f
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
        -0.013104376f
        :
        0.047904674f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_27 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
      -0.037760712f
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
        -0.010754626f
        :
        0.044792455f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_28 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
      -0.0349754f
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
        -0.009433124f
        :
        0.041977666f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_29 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
      -0.031164771f
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
        0.004308679f
        :
        0.039016303f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_30 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
      ((Double.isNaN(data[1]) || ((float)data[1]) < 2.65f) ?
        0.03543117f
        :
        -0.05422918f
      )
      :
      0.038545925f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_31 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
      -0.03555578f
      :
      ((Double.isNaN(data[0]) || ((float)data[0]) < 6.3500004f) ?
        0.032716595f
        :
        0.006841929f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_32 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
      -0.032576453f
      :
      ((Double.isNaN(data[0]) || ((float)data[0]) < 6.3500004f) ?
        0.030373937f
        :
        0.0065489267f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_33 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
        -0.038526107f
        :
        0.0034566484f
      )
      :
      0.037049565f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_34 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
      -0.031350084f
      :
      0.024609135f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_35 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
        -0.03586254f
        :
        0.0029147936f
      )
      :
      0.034228455f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_36 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[1]) || ((float)data[1]) < 2.65f) ?
      0.03798736f
      :
      ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
        -0.053041615f
        :
        0.028477294f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_37 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
        -0.03507714f
        :
        0.0015830144f
      )
      :
      0.035817027f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_38 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[1]) || ((float)data[1]) < 2.65f) ?
      0.037501156f
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
        -0.049159463f
        :
        0.030572448f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_39 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
      -0.029951561f
      :
      0.025186652f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_40 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[1]) || ((float)data[1]) < 2.65f) ?
      0.036515113f
      :
      ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
        -0.047730353f
        :
        0.02577398f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_41 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
        -0.0055414992f
        :
        -0.02082412f
      )
      :
      0.034319665f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_42 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
      -0.027862277f
      :
      0.02396258f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_43 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
      -0.024801465f
      :
      0.021743104f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_44 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
        -0.0054392307f
        :
        -0.020063581f
      )
      :
      0.032695733f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_45 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
      -0.024925191f
      :
      0.021524124f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_46 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
        -0.0045876508f
        :
        -0.018729974f
      )
      :
      0.030236369f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_47 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
      -0.024110816f
      :
      0.020359406f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_48 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
        -0.004887299f
        :
        -0.019169131f
      )
      :
      0.030489393f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_0_t_49 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
        -0.004613865f
        :
        -0.018084124f
      )
      :
      0.029368907f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_0 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      -0.21531104f
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
          ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
            0.42857146f
            :
            0.12857142f
          )
          :
          ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
            -0.12857145f
            :
            0.12857142f
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
          -7.663455E-9f
          :
          -0.21381217f
        )
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_1 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      -0.19161221f
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
          0.2872154f
          :
          ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
            -0.11965539f
            :
            0.121238194f
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
          0.011982666f
          :
          -0.19113852f
        )
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_2 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      -0.17550403f
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 5.05f) ?
            0.07849173f
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.25f) ?
              0.06684185f
              :
              0.24105743f
            )
          )
          :
          -0.03715564f
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
          0.010061415f
          :
          -0.17470442f
        )
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_3 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      -0.16360562f
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
          ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
            0.20451863f
            :
            0.046483487f
          )
          :
          ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
            -0.10969331f
            :
            0.092642024f
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
          0.009034463f
          :
          -0.16247705f
        )
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_4 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      -0.15413892f
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
          0.18694715f
          :
          -0.053264387f
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.9f) ?
            -0.13548003f
            :
            0.08859256f
          )
          :
          -0.15066254f
        )
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_5 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      -0.14601347f
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
          0.17250457f
          :
          -0.04719114f
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.9f) ?
            -0.12694477f
            :
            0.07991037f
          )
          :
          -0.14191703f
        )
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_6 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      -0.13852312f
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
          0.16198298f
          :
          -0.044376086f
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.9f) ?
            -0.11857388f
            :
            0.07438575f
          )
          :
          -0.13383763f
        )
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_7 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      -0.13121054f
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
          0.15330814f
          :
          -0.039566956f
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.9f) ?
            -0.1109901f
            :
            0.070431165f
          )
          :
          -0.12617521f
        )
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_8 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      -0.123804785f
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
          0.14580147f
          :
          -0.03517872f
        )
        :
        ((Double.isNaN(data[1]) || ((float)data[1]) < 3.15f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.6f) ?
            -0.13418226f
            :
            -0.021395506f
          )
          :
          0.0087980805f
        )
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_9 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 5.1499996f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
        -0.11619165f
        :
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.35f) ?
            0.016491072f
            :
            0.13854973f
          )
          :
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.9f) ?
            -0.10206806f
            :
            0.05554189f
          )
        )
      )
      :
      -0.12339401f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_10 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 5.1499996f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
        -0.10837799f
        :
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
            0.13155746f
            :
            0.01306629f
          )
          :
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.9f) ?
            -0.095006354f
            :
            0.05321872f
          )
        )
      )
      :
      -0.11684159f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_11 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 5.1499996f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
        -0.10047019f
        :
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
            0.12452725f
            :
            0.012794828f
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
            0.018213524f
            :
            -0.035122618f
          )
        )
      )
      :
      -0.11041882f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_12 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 5.1499996f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
        -0.09262984f
        :
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
            0.11755105f
            :
            0.012518024f
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
            0.020784235f
            :
            -0.031381913f
          )
        )
      )
      :
      -0.10425193f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_13 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 5.1499996f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 5.45f) ?
        -0.07356868f
        :
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.65f) ?
            0.01231891f
            :
            0.10509508f
          )
          :
          -0.011383802f
        )
      )
      :
      -0.09552697f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_14 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 5.1499996f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 5.45f) ?
        -0.065477304f
        :
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
          ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.6499996f) ?
              0.07104016f
              :
              -0.03160965f
            )
            :
            0.11912002f
          )
          :
          -0.009008711f
        )
      )
      :
      -0.08738066f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_15 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 5.1499996f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 5.45f) ?
        -0.058531027f
        :
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
          ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.6499996f) ?
              0.06644314f
              :
              -0.026468797f
            )
            :
            0.10936948f
          )
          :
          -0.008260034f
        )
      )
      :
      -0.08235543f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_16 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 5.45f) ?
        -0.052203894f
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
          0.09236723f
          :
          0.017984115f
        )
      )
      :
      ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
        0.008864448f
        :
        -0.059059504f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_17 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.45f) ?
      -0.0471517f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
          0.08310749f
          :
          0.01498666f
        )
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
          0.009156841f
          :
          -0.051393375f
        )
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_18 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.45f) ?
      -0.04351306f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
          0.07811822f
          :
          0.010139887f
        )
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
          0.010207403f
          :
          -0.045376822f
        )
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_19 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 5.45f) ?
        -0.03884898f
        :
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
          0.0026702003f
          :
          0.0747686f
        )
      )
      :
      -0.03196635f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_20 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 5.55f) ?
        -0.029460678f
        :
        0.049142905f
      )
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
        0.0041584466f
        :
        -0.03627529f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_21 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
        ((Double.isNaN(data[1]) || ((float)data[1]) < 2.65f) ?
          -0.028343681f
          :
          0.005448736f
        )
        :
        0.055892024f
      )
      :
      -0.027880916f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_22 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 5.55f) ?
        -0.027482292f
        :
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
          -0.006979891f
          :
          0.07098631f
        )
      )
      :
      -0.027507087f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_23 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 5.55f) ?
        -0.024835639f
        :
        0.04465202f
      )
      :
      -0.02238738f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_24 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
      -0.023765182f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
        0.041389108f
        :
        -0.01251977f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_25 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
      -0.023932887f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
        0.04017443f
        :
        -0.011971557f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_26 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 5.55f) ?
        -0.022557471f
        :
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
          -0.009923782f
          :
          0.06433097f
        )
      )
      :
      -0.024753831f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_27 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
      -0.021652848f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
        0.03367493f
        :
        -0.018465267f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_28 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 5.55f) ?
        -0.02261886f
        :
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
          -0.009347784f
          :
          0.063170664f
        )
      )
      :
      -0.023571802f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_29 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
      -0.021939594f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
        0.040045463f
        :
        -0.010550121f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_30 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 5.55f) ?
        -0.02229077f
        :
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
          -0.008718946f
          :
          0.06249365f
        )
      )
      :
      -0.024060955f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_31 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 5.55f) ?
        -0.02010414f
        :
        0.029872775f
      )
      :
      -0.022589559f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_32 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
      -0.020352395f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
        0.036393546f
        :
        -0.010252479f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_33 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 5.55f) ?
        -0.02013641f
        :
        ((Double.isNaN(data[3]) || ((float)data[3]) < 1.55f) ?
          -0.008428384f
          :
          0.05763858f
        )
      )
      :
      -0.022988867f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_34 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
      -0.02025721f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
        0.03670536f
        :
        -0.009478055f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_35 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
      -0.020223541f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
        0.02928597f
        :
        -0.012095152f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_36 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
      -0.01988782f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
        0.033151112f
        :
        -0.006172968f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_37 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
      0.021794453f
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
        -0.036533184f
        :
        0.013799856f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_38 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 5.55f) ?
        -0.019743409f
        :
        0.029761167f
      )
      :
      -0.021333138f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_39 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
      0.019072969f
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
        -0.03825457f
        :
        0.016835677f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_40 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
      -0.019209588f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
        0.031824052f
        :
        -0.007258437f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_41 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 5.6499996f) ?
        -0.012093725f
        :
        0.025538107f
      )
      :
      -0.022318289f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_42 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
      0.01755434f
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
        -0.03632964f
        :
        0.016249726f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_43 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
      -0.018602593f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
        0.030354243f
        :
        -0.0068845423f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_44 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[3]) || ((float)data[3]) < 1.75f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 5.6499996f) ?
        -0.01295024f
        :
        0.02581309f
      )
      :
      -0.021166764f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_45 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
      -0.018283743f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
        0.03061405f
        :
        -0.0072259307f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_46 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
      -0.01813011f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
        0.028716343f
        :
        -0.004763055f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_47 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
      -0.017133055f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
        0.027998881f
        :
        -0.0051737577f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_48 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
      -0.017036244f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
        0.026282435f
        :
        -0.0029987006f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_1_t_49 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
      0.017302187f
      :
      ((Double.isNaN(data[3]) || ((float)data[3]) < 1.6500001f) ?
        -0.03475795f
        :
        0.016437437f
      )
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_0 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.430622f
      :
      -0.22004892f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_1 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.29508278f
      :
      -0.19683747f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_2 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.23630679f
      :
      -0.1813366f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_3 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.20385234f
      :
      -0.17049491f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_4 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.18345241f
      :
      -0.16229746f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_5 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.16936812f
      :
      -0.15569985f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_6 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.15879954f
      :
      -0.1501053f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_7 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.15020491f
      :
      -0.14504465f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_8 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.1426671f
      :
      -0.14016874f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_9 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.13557972f
      :
      -0.13506499f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_10 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.12865451f
      :
      -0.12981202f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_11 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.12171906f
      :
      -0.12421722f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_12 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.11473041f
      :
      -0.11842058f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_13 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.107694656f
      :
      -0.11257698f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_14 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.101380005f
      :
      -0.10711715f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_15 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.095275715f
      :
      -0.10179033f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_16 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.08918202f
      :
      -0.09649854f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_17 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.08379894f
      :
      -0.09172585f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_18 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.07866776f
      :
      -0.087003425f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_19 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 3.4f) ?
      0.06778017f
      :
      -0.08080523f
    );
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_20 {
  static float score0(double[] data) {
    return     -0.012426118f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_21 {
  static float score0(double[] data) {
    return     -0.0114870705f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_22 {
  static float score0(double[] data) {
    return     -0.01000177f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_23 {
  static float score0(double[] data) {
    return     -0.010173048f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_24 {
  static float score0(double[] data) {
    return     -0.009726162f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_25 {
  static float score0(double[] data) {
    return     -0.009355036f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_26 {
  static float score0(double[] data) {
    return     -0.009472654f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_27 {
  static float score0(double[] data) {
    return     -0.009562665f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_28 {
  static float score0(double[] data) {
    return     -0.0095100375f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_29 {
  static float score0(double[] data) {
    return     -0.009630194f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_30 {
  static float score0(double[] data) {
    return     -0.0094389105f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_31 {
  static float score0(double[] data) {
    return     -0.009584291f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_32 {
  static float score0(double[] data) {
    return     -0.009257867f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_33 {
  static float score0(double[] data) {
    return     -0.00937758f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_34 {
  static float score0(double[] data) {
    return     -0.009351105f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_35 {
  static float score0(double[] data) {
    return     -0.009359802f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_36 {
  static float score0(double[] data) {
    return     -0.0092919f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_37 {
  static float score0(double[] data) {
    return     -0.009436508f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_38 {
  static float score0(double[] data) {
    return     -0.009736262f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_39 {
  static float score0(double[] data) {
    return     -0.0092526395f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_40 {
  static float score0(double[] data) {
    return     -0.00978165f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_41 {
  static float score0(double[] data) {
    return     -0.009821682f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_42 {
  static float score0(double[] data) {
    return     -0.008844325f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_43 {
  static float score0(double[] data) {
    return     -0.00935306f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_44 {
  static float score0(double[] data) {
    return     -0.009342066f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_45 {
  static float score0(double[] data) {
    return     -0.008475191f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_46 {
  static float score0(double[] data) {
    return     -0.008558554f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_47 {
  static float score0(double[] data) {
    return     -0.008337898f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_48 {
  static float score0(double[] data) {
    return     -0.008422081f;
  }
}

class xgboost_02091d16_b8d0_4cb5_b069_5155cb9f126f_Tree_g_2_t_49 {
  static float score0(double[] data) {
    return     -0.008211457f;
  }
}
