/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2020-06-11T14:13:36.941-04:00
  3.30.0.4
  
  Standalone prediction code with sample test data for XGBoostModel named xgboost_083c4083_1ae0_426d_b65a_2444df6724a8

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://192.168.1.200:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://192.168.1.200:54321/3/Models.java/xgboost-083c4083-1ae0-426d-b65a-2444df6724a8 > xgboost_083c4083_1ae0_426d_b65a_2444df6724a8.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m xgboost_083c4083_1ae0_426d_b65a_2444df6724a8.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;

@ModelPojo(name="xgboost_083c4083_1ae0_426d_b65a_2444df6724a8", algorithm="xgboost")
public class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8 extends GenModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Regression; }

  public boolean isSupervised() { return true; }
  public int nclasses() { return 1; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_xgboost_083c4083_1ae0_426d_b65a_2444df6724a8.VALUES;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* sepal_length */ null,
    /* sepal_width */ null,
    /* petal_length */ null,
    /* species */ null
  };
  // Prior class distribution
  public static final double[] PRIOR_CLASS_DISTRIB = null;
  // Class distribution used for model building
  public static final double[] MODEL_CLASS_DISTRIB = null;

  public xgboost_083c4083_1ae0_426d_b65a_2444df6724a8() { super(NAMES,DOMAINS,"species"); }
  public String getUUID() { return Long.toString(1122503504465022624L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    float preds_0 = 0f;
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_0.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_1.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_2.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_3.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_4.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_5.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_6.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_7.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_8.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_9.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_10.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_11.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_12.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_13.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_14.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_15.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_16.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_17.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_18.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_19.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_20.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_21.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_22.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_23.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_24.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_25.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_26.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_27.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_28.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_29.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_30.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_31.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_32.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_33.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_34.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_35.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_36.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_37.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_38.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_39.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_40.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_41.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_42.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_43.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_44.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_45.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_46.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_47.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_48.score0(data);
    preds_0 += xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_49.score0(data);
    preds_0 += 0.5f;
    preds[0] = preds_0;
    preds[0] = (float) preds[0];
    return preds;
  }
}
// The class representing training column names
class NamesHolder_xgboost_083c4083_1ae0_426d_b65a_2444df6724a8 implements java.io.Serializable {
  public static final String[] VALUES = new String[3];
  static {
    NamesHolder_xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_0.fill(VALUES);
  }
  static final class NamesHolder_xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "sepal_length";
      sa[1] = "sepal_width";
      sa[2] = "petal_length";
    }
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_0 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.4402174f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.45f) ?
            0.075f
            :
            -0.075f
          )
          :
          0.14625001f
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.25f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 3.1f) ?
              -0.12857144f
              :
              0.075f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.5f) ?
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.6f) ?
                0.075f
                :
                -0.075f
              )
              :
              0.10000001f
            )
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
              -0.112500004f
              :
              0.075f
            )
            :
            -0.1457143f
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_1 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.31102318f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.45f) ?
              0.063750006f
              :
              -0.063750006f
            )
            :
            0.103471875f
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
            0.063750006f
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.5f) ?
              -0.074285716f
              :
              0.06f
            )
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.2f) ?
            -0.08914285f
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.6f) ?
              0.063750006f
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.5f) ?
                -0.063750006f
                :
                0.06f
              )
            )
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
              -0.0871875f
              :
              0.063750006f
            )
            :
            -0.10324898f
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_2 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.21974465f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.45f) ?
              0.0541875f
              :
              -0.054187503f
            )
            :
            0.07320635f
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
            0.0541875f
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.5f) ?
              -0.05942857f
              :
              0.051f
            )
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.2f) ?
            -0.06774857f
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.6f) ?
              0.0541875f
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.5f) ?
                -0.054187503f
                :
                0.051f
              )
            )
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
              -0.067570314f
              :
              0.0541875f
            )
            :
            -0.07315928f
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_3 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.15525436f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.45f) ?
              0.046059377f
              :
              -0.046059377f
            )
            :
            0.05179349f
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
            0.046059377f
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.5f) ?
              -0.047542855f
              :
              0.043349996f
            )
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.2f) ?
            -0.05148891f
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.6f) ?
              0.046059377f
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.5f) ?
                -0.046059377f
                :
                0.043349996f
              )
            )
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
              -0.05236699f
              :
              0.046059377f
            )
            :
            -0.051838573f
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_4 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
      0.10969058f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.45f) ?
              0.039150473f
              :
              -0.039150473f
            )
            :
            0.036643885f
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
            0.039150473f
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.5f) ?
              -0.038034283f
              :
              0.036847502f
            )
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.2f) ?
            -0.03913157f
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.6f) ?
              0.039150473f
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.5f) ?
                -0.039150473f
                :
                0.036847502f
              )
            )
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
              -0.040584415f
              :
              0.039150473f
            )
            :
            -0.036731333f
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_5 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 3.4f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
        0.077498786f
        :
        0.029934106f
      )
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
          -0.0332779f
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
            0.025890566f
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
              0.0332779f
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.5f) ?
                -0.030427428f
                :
                0.03132037f
              )
            )
          )
        )
        :
        ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
            0.0332779f
            :
            -0.025285563f
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
            -0.035226446f
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
              0.03132037f
              :
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
                -0.013956494f
                :
                -0.026428288f
              )
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_6 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 3.4f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
        0.054754574f
        :
        0.023198932f
      )
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
          -0.028286215f
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
            0.01832779f
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
              0.02828622f
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.5f) ?
                -0.024341943f
                :
                0.026622312f
              )
            )
          )
        )
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
          -0.027617617f
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 5.2f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 3.05f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.5f) ?
                -5.332628E-4f
                :
                0.026622312f
              )
              :
              -0.012575852f
            )
            :
            -0.018635767f
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_7 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 3.4f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
        0.038685277f
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
          0.025307948f
          :
          0.0071002725f
        )
      )
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
          -0.024043282f
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.75f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
              0.0129741505f
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
                0.024043286f
                :
                -0.019473553f
              )
            )
            :
            0.022628967f
          )
        )
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
          -0.020713212f
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.45f) ?
              -0.014714673f
              :
              0.035451367f
            )
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.5f) ?
                0.028366212f
                :
                -0.006807933f
              )
              :
              ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
                -0.02742499f
                :
                -0.011801257f
              )
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_8 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 3.4f) ?
      0.026884392f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
          -0.02043679f
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.75f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
              0.009184335f
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
                0.020436797f
                :
                -0.015578843f
              )
            )
            :
            0.019234622f
          )
        )
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
          -0.015534909f
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 5.2f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.35f) ?
              -0.012507472f
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
                0.030133663f
                :
                -8.829767E-4f
              )
            )
            :
            -0.00983682f
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_9 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 3.4f) ?
      ((Double.isNaN(data[1]) || ((float)data[1]) < 2.35f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 4.75f) ?
          0.009937013f
          :
          2.2750498E-4f
        )
        :
        0.019358942f
      )
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
          -0.01737127f
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.75f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
              0.0065015354f
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
                0.017371275f
                :
                -0.012463073f
              )
            )
            :
            0.016349433f
          )
        )
        :
        ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
            0.02424373f
            :
            -0.010078687f
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.85f) ?
              -0.0037236682f
              :
              -0.021763394f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
              0.024531601f
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
                -1.6058609E-4f
                :
                -0.0074159824f
              )
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_10 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 3.4f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
        0.013821985f
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
          0.014575259f
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 5.05f) ?
            1.9337834E-4f
            :
            -0.002676344f
          )
        )
      )
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 6.6499996f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
            -0.014765581f
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
              ((Double.isNaN(data[1]) || ((float)data[1]) < 3.1f) ?
                0.0035020153f
                :
                0.009746183f
              )
              :
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.6f) ?
                0.0038923123f
                :
                -0.014640595f
              )
            )
          )
          :
          ((Double.isNaN(data[1]) || ((float)data[1]) < 3.05f) ?
            0.023165919f
            :
            0.0031511902f
          )
        )
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
          -0.012971407f
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
            0.0256377f
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.3500004f) ?
              -0.0072751413f
              :
              -0.004689105f
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_11 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 3.4f) ?
      0.009587179f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 6.6499996f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
            -0.012550744f
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
              ((Double.isNaN(data[1]) || ((float)data[1]) < 3.15f) ?
                0.0035680593f
                :
                0.0012019515f
              )
              :
              ((Double.isNaN(data[1]) || ((float)data[1]) < 3.1f) ?
                -0.0072591403f
                :
                0.01330365f
              )
            )
          )
          :
          ((Double.isNaN(data[1]) || ((float)data[1]) < 3.05f) ?
            0.018532729f
            :
            0.0025209547f
          )
        )
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
          -0.010052841f
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
            0.021792047f
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.2f) ?
              -0.006062005f
              :
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
                -0.0048182406f
                :
                -0.0030098876f
              )
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_12 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 3.4f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 2.45f) ?
        0.0069519146f
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
          0.010950897f
          :
          -0.0033244493f
        )
      )
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 6.6499996f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
            -0.010668132f
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
                0.006307052f
                :
                7.098629E-4f
              )
              :
              -0.007874999f
            )
          )
          :
          ((Double.isNaN(data[1]) || ((float)data[1]) < 3.05f) ?
            0.0148261795f
            :
            0.002016759f
          )
        )
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
          -0.0077909515f
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
            0.018523239f
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.2f) ?
              -0.004698054f
              :
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
                -0.0036618628f
                :
                -0.0021391702f
              )
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_13 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 3.4f) ?
      0.004828059f
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 6.6499996f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
            -0.009067913f
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.65f) ?
                0.0040938337f
                :
                3.2029237E-4f
              )
              :
              -0.006299999f
            )
          )
          :
          ((Double.isNaN(data[1]) || ((float)data[1]) < 3.05f) ?
            0.011860943f
            :
            0.0016134024f
          )
        )
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
          -0.0060379873f
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
            0.015744755f
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.2f) ?
              -0.003640992f
              :
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
                -0.0027830158f
                :
                -0.0015203387f
              )
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_14 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 3.4f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
        ((Double.isNaN(data[1]) || ((float)data[1]) < 2.65f) ?
          0.007834757f
          :
          0.0033031353f
        )
        :
        ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
          -0.0036251666f
          :
          0.003388561f
        )
      )
      :
      ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
        -0.0077077257f
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.6499996f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 3.1f) ?
              ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
                0.0014678027f
                :
                -0.004896758f
              )
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
                0.011153573f
                :
                7.5552467E-4f
              )
            )
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 3.05f) ?
              0.009488749f
              :
              0.0012907267f
            )
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
            -0.00467944f
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
              0.013383043f
              :
              ((Double.isNaN(data[2]) || ((float)data[2]) < 5.2f) ?
                -0.0028217689f
                :
                -0.0012759438f
              )
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_15 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 3.4f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 2.6f) ?
          0.0024602115f
          :
          0.007408843f
        )
        :
        ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
          -0.0029001355f
          :
          0.0024070574f
        )
      )
      :
      ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
        -0.006551567f
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.6499996f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 3.1f) ?
              ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
                0.0010404069f
                :
                -0.0035909563f
              )
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
                0.009480536f
                :
                6.0441496E-4f
              )
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.9f) ?
              0.0018823475f
              :
              0.00917067f
            )
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
            -0.0036265664f
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
              0.011375588f
              :
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.85f) ?
                -0.0017434658f
                :
                -7.798749E-4f
              )
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_16 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 3.4f) ?
      ((Double.isNaN(data[1]) || ((float)data[1]) < 2.45f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 4.7f) ?
            0.0016238273f
            :
            0.0062975143f
          )
          :
          -5.204559E-4f
        )
        :
        ((Double.isNaN(data[1]) || ((float)data[1]) < 2.7f) ?
          -0.0029597105f
          :
          0.0017349817f
        )
      )
      :
      ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
        -0.0055688317f
        :
        ((Double.isNaN(data[1]) || ((float)data[1]) < 2.45f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
            -0.0010860035f
            :
            -0.0052151177f
          )
          :
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.0f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 5.6499996f) ?
                -8.4466935E-4f
                :
                2.0143314E-4f
              )
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.5f) ?
                0.020825217f
                :
                4.632844E-5f
              )
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
                5.5009976E-4f
                :
                0.0039539863f
              )
              :
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
                -0.007808822f
                :
                2.0003067E-6f
              )
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_17 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 3.4f) ?
      ((Double.isNaN(data[1]) || ((float)data[1]) < 2.45f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 4.7f) ?
            0.001380247f
            :
            0.0053528845f
          )
          :
          -4.423857E-4f
        )
        :
        ((Double.isNaN(data[1]) || ((float)data[1]) < 2.7f) ?
          -0.0025157512f
          :
          0.0012260565f
        )
      )
      :
      ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
        -0.0047335066f
        :
        ((Double.isNaN(data[1]) || ((float)data[1]) < 2.45f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
            -8.067472E-4f
            :
            -0.00443285f
          )
          :
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.0f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 5.6499996f) ?
                -6.757259E-4f
                :
                1.7121815E-4f
              )
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.5f) ?
                0.017701436f
                :
                3.9379174E-5f
              )
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
              ((Double.isNaN(data[1]) || ((float)data[1]) < 3.35f) ?
                0.0011396171f
                :
                -2.3043752E-4f
              )
              :
              ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
                -0.0044420143f
                :
                4.52995E-5f
              )
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_18 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 6.6499996f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.65f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.65f) ?
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.45f) ?
                0.0012280993f
                :
                -0.001778713f
              )
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
                9.023905E-4f
                :
                8.07345E-6f
              )
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 5.6499996f) ?
                0.0018222636f
                :
                1.4553542E-4f
              )
              :
              0.008131662f
            )
          )
          :
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.6f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.4f) ?
              ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
                -5.243987E-4f
                :
                -0.0037679223f
              )
              :
              0.015046218f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
                -1.2519956E-4f
                :
                9.996701E-4f
              )
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.1499996f) ?
                -0.0042437846f
                :
                -0.012861105f
              )
            )
          )
        )
        :
        ((Double.isNaN(data[1]) || ((float)data[1]) < 3.05f) ?
          0.006924963f
          :
          4.2777063E-4f
        )
      )
      :
      ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
        ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
          -0.0034488349f
          :
          -7.158554E-4f
        )
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
          0.009069353f
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 5.2f) ?
            -0.0019497721f
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.3500004f) ?
              2.4235877E-4f
              :
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.85f) ?
                -1.8991076E-4f
                :
                -5.2295346E-4f
              )
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_19 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[1]) || ((float)data[1]) < 2.25f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
        -5.3784554E-4f
        :
        -0.003202734f
      )
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.7f) ?
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.45f) ?
                9.874105E-4f
                :
                -0.0023622068f
              )
              :
              0.012789283f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
                8.295144E-4f
                :
                -3.192668E-4f
              )
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.2f) ?
                0.0010281679f
                :
                -0.012232852f
              )
            )
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.2f) ?
            1.237051E-4f
            :
            0.006749225f
          )
        )
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
            -0.0027590678f
            :
            -6.084771E-4f
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
            0.007708955f
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.2f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.4f) ?
                -0.0021152815f
                :
                -6.045767E-4f
              )
              :
              ((Double.isNaN(data[2]) || ((float)data[2]) < 5.3500004f) ?
                1.9388703E-4f
                :
                -3.2323034E-4f
              )
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_20 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[1]) || ((float)data[1]) < 2.25f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
        -4.1682424E-4f
        :
        -0.0027223239f
      )
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.7f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.45f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 4.7f) ?
                8.4089045E-4f
                :
                0.0042176307f
              )
              :
              ((Double.isNaN(data[2]) || ((float)data[2]) < 3.85f) ?
                -0.0014357758f
                :
                6.169081E-6f
              )
            )
            :
            -0.0034023428f
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
            0.010870886f
            :
            1.4372854E-4f
          )
        )
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 6.1499996f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.0f) ?
              ((Double.isNaN(data[2]) || ((float)data[2]) < 4.7f) ?
                3.8184435E-4f
                :
                0.0013946987f
              )
              :
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
                -0.0022072543f
                :
                -5.172055E-4f
              )
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
              ((Double.isNaN(data[1]) || ((float)data[1]) < 3.1f) ?
                -1.17552285E-4f
                :
                0.006787482f
              )
              :
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
                0.0043271137f
                :
                -7.2403054E-4f
              )
            )
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.3500004f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.85f) ?
              ((Double.isNaN(data[2]) || ((float)data[2]) < 5.0f) ?
                -0.009033672f
                :
                -0.0017979892f
              )
              :
              ((Double.isNaN(data[2]) || ((float)data[2]) < 5.1499996f) ?
                3.9209132E-4f
                :
                -2.1965169E-4f
              )
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
              ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
                7.0183276E-4f
                :
                0.004896969f
              )
              :
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.85f) ?
                -2.451166E-5f
                :
                -3.0075133E-4f
              )
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_21 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[1]) || ((float)data[1]) < 2.25f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
        -3.2302737E-4f
        :
        -0.0023139752f
      )
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.7f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.45f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 4.7f) ?
                7.147551E-4f
                :
                0.003584987f
              )
              :
              ((Double.isNaN(data[2]) || ((float)data[2]) < 3.85f) ?
                -0.0010911942f
                :
                4.7743324E-6f
              )
            )
            :
            -0.0028919913f
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
            0.009240255f
            :
            1.14982824E-4f
          )
        )
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 6.1499996f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.0f) ?
              ((Double.isNaN(data[2]) || ((float)data[2]) < 4.7f) ?
                2.6920528E-4f
                :
                0.001185494f
              )
              :
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
                -0.0017658034f
                :
                -4.3962468E-4f
              )
            )
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 3.1f) ?
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.95f) ?
                0.0020565984f
                :
                -0.001789674f
              )
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
                0.0057693603f
                :
                -2.0599366E-5f
              )
            )
          )
          :
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.3500004f) ?
              -0.009042872f
              :
              8.598102E-5f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
              ((Double.isNaN(data[2]) || ((float)data[2]) < 4.9f) ?
                2.2523111E-4f
                :
                0.0050022933f
              )
              :
              ((Double.isNaN(data[2]) || ((float)data[2]) < 5.2f) ?
                -0.0010817788f
                :
                -1.6886115E-4f
              )
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_22 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[1]) || ((float)data[1]) < 2.25f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
        -2.503395E-4f
        :
        -0.001966879f
      )
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.7f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.45f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 4.7f) ?
                6.0753827E-4f
                :
                0.00304724f
              )
              :
              ((Double.isNaN(data[2]) || ((float)data[2]) < 3.85f) ?
                -8.292962E-4f
                :
                3.7014486E-6f
              )
            )
            :
            -0.0024581926f
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
            0.007854215f
            :
            9.198626E-5f
          )
        )
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 6.1499996f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.0f) ?
              ((Double.isNaN(data[2]) || ((float)data[2]) < 4.7f) ?
                1.897943E-4f
                :
                0.0010076698f
              )
              :
              -0.0012463225f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
              ((Double.isNaN(data[1]) || ((float)data[1]) < 3.1f) ?
                1.6853213E-4f
                :
                0.0049039545f
              )
              :
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
                0.0030503706f
                :
                -6.255122E-4f
              )
            )
          )
          :
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.3500004f) ?
              -0.0076864413f
              :
              6.878482E-5f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
              ((Double.isNaN(data[2]) || ((float)data[2]) < 4.9f) ?
                1.6441694E-4f
                :
                0.0042519453f
              )
              :
              ((Double.isNaN(data[2]) || ((float)data[2]) < 5.2f) ?
                -8.383786E-4f
                :
                -1.2001203E-4f
              )
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_23 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[1]) || ((float)data[1]) < 2.25f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
        -1.9401313E-4f
        :
        -0.0016718471f
      )
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.7f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.2f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 4.7f) ?
                5.1641464E-4f
                :
                0.0025901557f
              )
              :
              ((Double.isNaN(data[2]) || ((float)data[2]) < 3.85f) ?
                -6.3025474E-4f
                :
                2.8465988E-4f
              )
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.6000004f) ?
              -0.0020894639f
              :
              -4.212499E-4f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
            0.006676081f
            :
            7.3589E-5f
          )
        )
        :
        ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
              ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
                1.0940731E-4f
                :
                -0.0011633784f
              )
              :
              0.0051374943f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.1000004f) ?
              -0.006533475f
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.25f) ?
                -0.0014770523f
                :
                5.5027856E-5f
              )
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
                3.1231294E-4f
                :
                -1.6267273E-4f
              )
              :
              0.0036141516f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.2f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.4f) ?
                -9.5133326E-4f
                :
                -3.9479637E-5f
              )
              :
              ((Double.isNaN(data[2]) || ((float)data[2]) < 5.3500004f) ?
                1.3755033E-4f
                :
                -9.8642224E-5f
              )
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_24 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[1]) || ((float)data[1]) < 2.25f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
        -1.5034676E-4f
        :
        -0.00142107f
      )
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.7f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.2f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 4.7f) ?
                4.3895247E-4f
                :
                0.0022016289f
              )
              :
              ((Double.isNaN(data[2]) || ((float)data[2]) < 3.15f) ?
                -9.192467E-4f
                :
                2.1117927E-5f
              )
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.6000004f) ?
              -0.0017760441f
              :
              -3.5805703E-4f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
            0.0056746695f
            :
            5.8871203E-5f
          )
        )
        :
        ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
              ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
                8.068085E-5f
                :
                -9.307026E-4f
              )
              :
              0.004366869f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.1000004f) ?
              -0.005553454f
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.25f) ?
                -0.0012554944f
                :
                4.402228E-5f
              )
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.3500004f) ?
                8.566901E-5f
                :
                6.425423E-4f
              )
              :
              0.0030720325f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.2f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.4f) ?
                -7.6106656E-4f
                :
                -3.158371E-5f
              )
              :
              -5.9289116E-5f
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_25 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[1]) || ((float)data[1]) < 2.25f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
        -1.16524105E-4f
        :
        -0.0012079095f
      )
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.7f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.2f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 4.7f) ?
                3.7311317E-4f
                :
                0.0018713862f
              )
              :
              ((Double.isNaN(data[2]) || ((float)data[2]) < 3.15f) ?
                -7.813633E-4f
                :
                1.5842916E-5f
              )
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.6000004f) ?
              -0.0015096376f
              :
              -3.0434132E-4f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
            0.0048234705f
            :
            4.709696E-5f
          )
        )
        :
        ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
              ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
                5.949587E-5f
                :
                -7.4456213E-4f
              )
              :
              0.0037118376f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.1000004f) ?
              -0.004720436f
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.25f) ?
                -0.0010671703f
                :
                3.5217818E-5f
              )
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
                1.9505473E-4f
                :
                -1.9654234E-4f
              )
              :
              0.002611229f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.3500004f) ?
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.85f) ?
                -6.088533E-4f
                :
                -6.9699054E-5f
              )
              :
              -3.6179925E-5f
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_26 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[1]) || ((float)data[1]) < 2.25f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
        -9.030998E-5f
        :
        -0.0010267231f
      )
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.7f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.2f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 4.7f) ?
                3.171444E-4f
                :
                0.0015906752f
              )
              :
              ((Double.isNaN(data[2]) || ((float)data[2]) < 3.15f) ?
                -6.6415075E-4f
                :
                1.1879206E-5f
              )
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.6000004f) ?
              -0.0012831918f
              :
              -2.5869012E-4f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
            0.0040999535f
            :
            3.7677568E-5f
          )
        )
        :
        ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
              ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
                4.388094E-5f
                :
                -5.956497E-4f
              )
              :
              0.0031550648f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.1000004f) ?
              -0.0040123705f
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.25f) ?
                -9.070947E-4f
                :
                2.8174256E-5f
              )
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 2.75f) ?
            -6.219228E-5f
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
              ((Double.isNaN(data[1]) || ((float)data[1]) < 3.1f) ?
                2.2227473E-4f
                :
                0.0040794075f
              )
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
                -0.0021995f
                :
                1.7405885E-4f
              )
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_27 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 5.3500004f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 6.55f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 6.1499996f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.45f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
                0.0010811031f
                :
                -2.0885469E-4f
              )
              :
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
                -4.3611455E-4f
                :
                -1.9624833E-5f
              )
            )
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 3.1f) ?
              ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
                -3.881456E-4f
                :
                0.0026818067f
              )
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
                0.0034674974f
                :
                4.4726732E-4f
              )
            )
          )
          :
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.6f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.4f) ?
              -1.1928082E-4f
              :
              0.0034849585f
            )
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.85f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.3500004f) ?
                -0.00308488f
                :
                1.396533E-4f
              )
              :
              ((Double.isNaN(data[1]) || ((float)data[1]) < 3.0500002f) ?
                4.4195654E-4f
                :
                2.624873E-5f
              )
            )
          )
        )
        :
        ((Double.isNaN(data[1]) || ((float)data[1]) < 3.05f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.6499996f) ?
            3.5529138E-4f
            :
            0.0019602955f
          )
          :
          5.2397976E-5f
        )
      )
      :
      ((Double.isNaN(data[0]) || ((float)data[0]) < 6.2f) ?
        -7.710305E-4f
        :
        -9.096363E-5f
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_28 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 5.3500004f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 6.55f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.45f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 4.7f) ?
                1.07413536E-4f
                :
                0.0011899085f
              )
              :
              -1.5872956E-4f
            )
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 5.3f) ?
                -0.0010162794f
                :
                2.7157913E-4f
              )
              :
              ((Double.isNaN(data[2]) || ((float)data[2]) < 5.0f) ?
                4.419535E-6f
                :
                -2.8891713E-4f
              )
            )
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 3.1f) ?
              7.917881E-5f
              :
              0.0029473724f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.1499996f) ?
                8.29424E-4f
                :
                1.2342632E-4f
              )
              :
              ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
                -0.0036774953f
                :
                3.166956E-4f
              )
            )
          )
        )
        :
        ((Double.isNaN(data[1]) || ((float)data[1]) < 3.05f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.9f) ?
            4.396543E-4f
            :
            0.0018993975f
          )
          :
          4.060926E-5f
        )
      )
      :
      ((Double.isNaN(data[0]) || ((float)data[0]) < 6.2f) ?
        -6.5537594E-4f
        :
        -6.4615546E-5f
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_29 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[1]) || ((float)data[1]) < 2.25f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
        -7.582605E-5f
        :
        -8.619972E-4f
      )
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.7f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.2f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 4.7f) ?
                9.13024E-5f
                :
                0.0010114253f
              )
              :
              ((Double.isNaN(data[2]) || ((float)data[2]) < 3.85f) ?
                -1.9258978E-4f
                :
                2.5087595E-4f
              )
            )
            :
            -7.288996E-4f
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
            0.0029147118f
            :
            6.2153515E-5f
          )
        )
        :
        ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
              ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
                3.6361816E-5f
                :
                -4.1481134E-4f
              )
              :
              0.002232036f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.1000004f) ?
              -0.0029952875f
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.25f) ?
                -5.5706955E-4f
                :
                -7.5375724E-6f
              )
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 3.8f) ?
            -3.8120023E-5f
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
              ((Double.isNaN(data[1]) || ((float)data[1]) < 3.1f) ?
                1.9405916E-4f
                :
                0.0025052638f
              )
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
                -0.0015285382f
                :
                1.346331E-4f
              )
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_30 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 5.3500004f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 6.6499996f) ?
        ((Double.isNaN(data[1]) || ((float)data[1]) < 2.25f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
            -5.87672E-5f
            :
            -7.326976E-4f
          )
          :
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.7f) ?
              ((Double.isNaN(data[2]) || ((float)data[2]) < 4.45f) ?
                1.5226185E-4f
                :
                -7.63519E-4f
              )
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.0f) ?
                3.5316763E-5f
                :
                0.002477503f
              )
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.1499996f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
                -8.49206E-6f
                :
                6.4552546E-4f
              )
              :
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.85f) ?
                -0.0015374853f
                :
                1.4339291E-4f
              )
            )
          )
        )
        :
        ((Double.isNaN(data[1]) || ((float)data[1]) < 3.05f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.75f) ?
            0.0015942872f
            :
            3.6681892E-4f
          )
          :
          1.1804295E-6f
        )
      )
      :
      ((Double.isNaN(data[0]) || ((float)data[0]) < 6.2f) ?
        -4.735091E-4f
        :
        -8.267597E-5f
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_31 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[1]) || ((float)data[1]) < 2.25f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
        -4.554391E-5f
        :
        -6.22793E-4f
      )
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.7f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.2f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 4.7f) ?
                5.477071E-5f
                :
                8.3686714E-4f
              )
              :
              ((Double.isNaN(data[2]) || ((float)data[2]) < 3.85f) ?
                -1.828909E-4f
                :
                1.702428E-4f
              )
            )
            :
            -5.2199623E-4f
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
            0.002105874f
            :
            5.4458735E-5f
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
            -1.9986708E-5f
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.25f) ?
              6.3470233E-4f
              :
              9.9893135E-5f
            )
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.0f) ?
              0.0018275452f
              :
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
                -3.3015065E-4f
                :
                1.4656043E-4f
              )
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.55f) ?
                -0.0024667536f
                :
                3.1179786E-4f
              )
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
                0.001800406f
                :
                -7.708565E-6f
              )
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_32 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 5.3500004f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.3f) ?
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.45f) ?
                1.6681297E-4f
                :
                -1.4264882E-5f
              )
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 5.15f) ?
                -5.706917E-4f
                :
                -4.4138433E-5f
              )
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.25f) ?
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.85f) ?
                1.3104916E-4f
                :
                5.379558E-4f
              )
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.3500004f) ?
                -9.855033E-5f
                :
                1.1728109E-4f
              )
            )
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
            0.0017585189f
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.1f) ?
              -0.003083829f
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.5f) ?
                -2.462594E-4f
                :
                2.6502908E-4f
              )
            )
          )
        )
        :
        ((Double.isNaN(data[1]) || ((float)data[1]) < 2.35f) ?
          -5.29374E-4f
          :
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.6f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.0f) ?
              2.185044E-5f
              :
              0.0017899901f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.2f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
                6.5172855E-5f
                :
                0.0014126389f
              )
              :
              ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
                -0.0019453585f
                :
                3.3649968E-4f
              )
            )
          )
        )
      )
      :
      ((Double.isNaN(data[0]) || ((float)data[0]) < 6.2f) ?
        -4.0132646E-4f
        :
        -5.713873E-5f
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_33 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[1]) || ((float)data[1]) < 2.25f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
        -6.746203E-5f
        :
        -4.499679E-4f
      )
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.7f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.45f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 4.7f) ?
                2.1547079E-5f
                :
                6.863147E-4f
              )
              :
              ((Double.isNaN(data[2]) || ((float)data[2]) < 3.15f) ?
                -3.1104684E-4f
                :
                1.6655242E-5f
              )
            )
            :
            -4.8508795E-4f
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
            0.001521492f
            :
            4.7095815E-5f
          )
        )
        :
        ((Double.isNaN(data[1]) || ((float)data[1]) < 2.65f) ?
          -2.0385165E-4f
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.1499996f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
              ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
                3.949665E-5f
                :
                -7.5100886E-4f
              )
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
                4.9531365E-5f
                :
                0.0011301121f
              )
            )
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.3500004f) ?
                -0.0016535547f
                :
                2.5363575E-4f
              )
              :
              ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
                2.913365E-4f
                :
                -8.1671475E-5f
              )
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_34 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[1]) || ((float)data[1]) < 2.25f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 6.1f) ?
        -2.7242684E-4f
        :
        5.781949E-5f
      )
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.7f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.45f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 4.7f) ?
                1.8310548E-5f
                :
                5.8337155E-4f
              )
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 5.3f) ?
                -2.1398069E-4f
                :
                3.3289194E-5f
              )
            )
            :
            -4.1232476E-4f
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.95f) ?
            0.0012932718f
            :
            3.767665E-5f
          )
        )
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 6.55f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.1499996f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
              ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
                2.3005348E-5f
                :
                -6.008061E-4f
              )
              :
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.65f) ?
                -3.1054975E-4f
                :
                4.143558E-4f
              )
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.2f) ?
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
                -0.0014055214f
                :
                -2.1699844E-4f
              )
              :
              2.4671479E-5f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.9f) ?
              5.4422024E-5f
              :
              0.0012621135f
            )
            :
            -3.3115557E-5f
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_35 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.7f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.45f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 3.15f) ?
              -4.185083E-5f
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 4.95f) ?
                4.9586897E-4f
                :
                1.3018595E-5f
              )
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.15f) ?
              -3.5047607E-4f
              :
              -2.2289158E-5f
            )
          )
          :
          2.406897E-4f
        )
        :
        ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
          -3.6993256E-4f
          :
          4.5217363E-5f
        )
      )
      :
      ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
        ((Double.isNaN(data[1]) || ((float)data[1]) < 3.1f) ?
          -6.28531E-5f
          :
          0.0016975165f
        )
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.95f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.45f) ?
              ((Double.isNaN(data[2]) || ((float)data[2]) < 4.5f) ?
                3.312528E-5f
                :
                -3.416087E-4f
              )
              :
              ((Double.isNaN(data[1]) || ((float)data[1]) < 2.8000002f) ?
                0.0010867775f
                :
                2.2062958E-4f
              )
            )
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 3.2f) ?
              -0.0024184827f
              :
              2.0294488E-4f
            )
          )
          :
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.4f) ?
              4.9471856E-7f
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.5f) ?
                0.0010992766f
                :
                3.9354978E-5f
              )
            )
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.3500004f) ?
                -9.7244035E-4f
                :
                1.2545771E-4f
              )
              :
              ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
                2.582634E-4f
                :
                -4.9820253E-5f
              )
            )
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_36 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 6.6499996f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.7f) ?
              -1.475319E-5f
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 5.6499996f) ?
                3.1907408E-4f
                :
                -3.0246454E-5f
              )
            )
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
              -2.9594603E-4f
              :
              3.8434755E-5f
            )
          )
          :
          ((Double.isNaN(data[1]) || ((float)data[1]) < 3.1f) ?
            -5.3429605E-5f
            :
            0.0014428855f
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.6499996f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.1499996f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.85f) ?
              5.974174E-5f
              :
              4.6870264E-4f
            )
            :
            1.911521E-5f
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
              -0.0020557102f
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.1499996f) ?
                4.1258336E-5f
                :
                -2.5762458E-4f
              )
            )
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.15f) ?
                -2.903674E-4f
                :
                9.343833E-4f
              )
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
                9.2376175E-4f
                :
                -1.6661185E-4f
              )
            )
          )
        )
      )
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.9f) ?
          -1.795739E-5f
          :
          0.0010340542f
        )
        :
        -8.340535E-6f
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_37 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 6.3500004f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 5.8500004f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
            -3.2741466E-6f
            :
            -1.6123283E-4f
          )
          :
          ((Double.isNaN(data[1]) || ((float)data[1]) < 3.1f) ?
            -4.541874E-5f
            :
            0.001226449f
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.25f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.95f) ?
              8.148104E-5f
              :
              4.061699E-4f
            )
            :
            -9.328127E-5f
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.1f) ?
              -0.0017473536f
              :
              -2.2056706E-4f
            )
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.55f) ?
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.15f) ?
                -2.468123E-4f
                :
                7.942289E-4f
              )
              :
              ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
                7.851988E-4f
                :
                -3.0943347E-4f
              )
            )
          )
        )
      )
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 3.05f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 5.4f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.9f) ?
            6.0367587E-5f
            :
            7.313366E-4f
          )
          :
          2.9475166E-5f
        )
        :
        -4.5890858E-5f
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_38 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 4.8500004f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 5.95f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.65f) ?
          -1.0360537E-5f
          :
          0.0010424852f
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.75f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.25f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.95f) ?
              6.0090424E-5f
              :
              3.249407E-4f
            )
            :
            -6.9238995E-5f
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.1f) ?
            -0.0014852505f
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.5f) ?
              -1.87482E-4f
              :
              1.2830795E-4f
            )
          )
        )
      )
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 5.05f) ?
        ((Double.isNaN(data[1]) || ((float)data[1]) < 2.75f) ?
          ((Double.isNaN(data[1]) || ((float)data[1]) < 2.6f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.15f) ?
              -1.5667256E-4f
              :
              6.7509414E-4f
            )
            :
            -9.774204E-4f
          )
          :
          6.093301E-4f
        )
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 6.05f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 5.9f) ?
            -1.2495545E-4f
            :
            6.67423E-4f
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 5.2f) ?
            -2.032832E-4f
            :
            2.7028545E-5f
          )
        )
      )
    );
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_39 {
  static float score0(double[] data) {
    return     7.96193E-6f;
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_40 {
  static float score0(double[] data) {
    return     5.5975033E-6f;
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_41 {
  static float score0(double[] data) {
    return     3.941112E-6f;
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_42 {
  static float score0(double[] data) {
    return     2.7573315E-6f;
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_43 {
  static float score0(double[] data) {
    return     1.9277243E-6f;
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_44 {
  static float score0(double[] data) {
    return     1.3577039E-6f;
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_45 {
  static float score0(double[] data) {
    return     9.483992E-7f;
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_46 {
  static float score0(double[] data) {
    return     6.649244E-7f;
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_47 {
  static float score0(double[] data) {
    return     4.5955048E-7f;
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_48 {
  static float score0(double[] data) {
    return     3.1926734E-7f;
  }
}

class xgboost_083c4083_1ae0_426d_b65a_2444df6724a8_Tree_g_0_t_49 {
  static float score0(double[] data) {
    return     2.3077534E-7f;
  }
}

