/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2020-06-03T11:05:59.367-04:00
  3.30.0.4
  
  Standalone prediction code with sample test data for GLMModel named glm_6cf0c852_0ab5_4c33_9422_e13ce5c03d44

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://192.168.1.11:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://192.168.1.11:54321/3/Models.java/glm-6cf0c852-0ab5-4c33-9422-e13ce5c03d44 > glm_6cf0c852_0ab5_4c33_9422_e13ce5c03d44.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m glm_6cf0c852_0ab5_4c33_9422_e13ce5c03d44.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;

@ModelPojo(name="glm_6cf0c852_0ab5_4c33_9422_e13ce5c03d44", algorithm="glm")
public class glm_6cf0c852_0ab5_4c33_9422_e13ce5c03d44 extends GenModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Regression; }

  public boolean isSupervised() { return true; }
  public int nfeatures() { return 5; }
  public int nclasses() { return 1; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_glm_6cf0c852_0ab5_4c33_9422_e13ce5c03d44.VALUES;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* current_player_score */ null,
    /* opponent_score */ null,
    /* current_player_deadwood */ null,
    /* current_player_num_hit_cards */ null,
    /* num_nearby_opponent_cards */ null,
    /* is_current_player_game_winner */ null
  };
  // Prior class distribution
  public static final double[] PRIOR_CLASS_DISTRIB = null;
  // Class distribution used for model building
  public static final double[] MODEL_CLASS_DISTRIB = null;

  public glm_6cf0c852_0ab5_4c33_9422_e13ce5c03d44() { super(NAMES,DOMAINS,"is_current_player_game_winner"); }
  public String getUUID() { return Long.toString(-7145752018656420276L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    final double [] b = BETA.VALUES;
    for(int i = 0; i < 0; ++i) if(Double.isNaN(data[i])) data[i] = CAT_MODES.VALUES[i];
    for(int i = 0; i < 5; ++i) if(Double.isNaN(data[i + 0])) data[i+0] = NUM_MEANS.VALUES[i];
    double eta = 0.0;
    for(int i = 0; i < CATOFFS.length-1; ++i) {
      int ival = (int)data[i];
      if(ival != data[i]) throw new IllegalArgumentException("categorical value out of range");
      ival += CATOFFS[i];
      if(ival < CATOFFS[i + 1])
        eta += b[ival];
    }
    for(int i = 0; i < b.length-1-0; ++i)
    eta += b[0+i]*data[i];
    eta += b[b.length-1]; // reduce intercept
    double mu = hex.genmodel.GenModel.GLM_identityInv(eta);
    preds[0] = mu;
    return preds;
  }
    public static class BETA implements java.io.Serializable {
      public static final double[] VALUES = new double[6];
      static {
        BETA_0.fill(VALUES);
      }
      static final class BETA_0 implements java.io.Serializable {
        static final void fill(double[] sa) {
          sa[0] = 0.008838312367532023;
          sa[1] = -0.008857622804310081;
          sa[2] = -0.002426771373045845;
          sa[3] = 0.0019041196796409248;
          sa[4] = -0.00561410644691002;
          sa[5] = 0.5971563122722667;
        }
      }
}
// Imputed numeric values
    static class NUM_MEANS implements java.io.Serializable {
      public static final double[] VALUES = new double[5];
      static {
        NUM_MEANS_0.fill(VALUES);
      }
      static final class NUM_MEANS_0 implements java.io.Serializable {
        static final void fill(double[] sa) {
          sa[0] = 36.13331758173602;
          sa[1] = 36.134380814554476;
          sa[2] = 35.324788091792435;
          sa[3] = 5.390619923801648;
          sa[4] = 2.5416875867568445;
        }
      }
}
// Imputed categorical values.
    static class CAT_MODES implements java.io.Serializable {
      public static final int[] VALUES = new int[0];
      static {
      }
}
    // Categorical Offsets
    public static final int[] CATOFFS = {0};
}
// The class representing training column names
class NamesHolder_glm_6cf0c852_0ab5_4c33_9422_e13ce5c03d44 implements java.io.Serializable {
  public static final String[] VALUES = new String[5];
  static {
    NamesHolder_glm_6cf0c852_0ab5_4c33_9422_e13ce5c03d44_0.fill(VALUES);
  }
  static final class NamesHolder_glm_6cf0c852_0ab5_4c33_9422_e13ce5c03d44_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "current_player_score";
      sa[1] = "opponent_score";
      sa[2] = "current_player_deadwood";
      sa[3] = "current_player_num_hit_cards";
      sa[4] = "num_nearby_opponent_cards";
    }
  }
}

