/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2020-06-12T14:37:19.869-04:00
  3.30.0.4
  
  Standalone prediction code with sample test data for XGBoostModel named xgboost_03e1a270_ee21_4887_bd76_18de3493c21a

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://192.168.1.200:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://192.168.1.200:54321/3/Models.java/xgboost-03e1a270-ee21-4887-bd76-18de3493c21a > xgboost_03e1a270_ee21_4887_bd76_18de3493c21a.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m xgboost_03e1a270_ee21_4887_bd76_18de3493c21a.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;

@ModelPojo(name="xgboost_03e1a270_ee21_4887_bd76_18de3493c21a", algorithm="xgboost")
public class xgboost_03e1a270_ee21_4887_bd76_18de3493c21a extends GenModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Regression; }

  public boolean isSupervised() { return true; }
  public int nclasses() { return 1; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_xgboost_03e1a270_ee21_4887_bd76_18de3493c21a.VALUES;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* current_player_deadwood */ null,
    /* num_melds */ null,
    /* turns_taken */ null,
    /* is_current_player_hand_winner */ null
  };
  // Prior class distribution
  public static final double[] PRIOR_CLASS_DISTRIB = null;
  // Class distribution used for model building
  public static final double[] MODEL_CLASS_DISTRIB = null;

  public xgboost_03e1a270_ee21_4887_bd76_18de3493c21a() { super(NAMES,DOMAINS,"is_current_player_hand_winner"); }
  public String getUUID() { return Long.toString(-4591487705361236032L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    float preds_0 = 0f;
    preds_0 += xgboost_03e1a270_ee21_4887_bd76_18de3493c21a_Tree_g_0_t_0.score0(data);
    preds_0 += xgboost_03e1a270_ee21_4887_bd76_18de3493c21a_Tree_g_0_t_1.score0(data);
    preds_0 += xgboost_03e1a270_ee21_4887_bd76_18de3493c21a_Tree_g_0_t_2.score0(data);
    preds_0 += xgboost_03e1a270_ee21_4887_bd76_18de3493c21a_Tree_g_0_t_3.score0(data);
    preds_0 += xgboost_03e1a270_ee21_4887_bd76_18de3493c21a_Tree_g_0_t_4.score0(data);
    preds_0 += xgboost_03e1a270_ee21_4887_bd76_18de3493c21a_Tree_g_0_t_5.score0(data);
    preds_0 += xgboost_03e1a270_ee21_4887_bd76_18de3493c21a_Tree_g_0_t_6.score0(data);
    preds_0 += xgboost_03e1a270_ee21_4887_bd76_18de3493c21a_Tree_g_0_t_7.score0(data);
    preds_0 += xgboost_03e1a270_ee21_4887_bd76_18de3493c21a_Tree_g_0_t_8.score0(data);
    preds_0 += xgboost_03e1a270_ee21_4887_bd76_18de3493c21a_Tree_g_0_t_9.score0(data);
    preds_0 += 0.5f;
    preds[0] = preds_0;
    preds[0] = (float) preds[0];
    return preds;
  }
}
// The class representing training column names
class NamesHolder_xgboost_03e1a270_ee21_4887_bd76_18de3493c21a implements java.io.Serializable {
  public static final String[] VALUES = new String[3];
  static {
    NamesHolder_xgboost_03e1a270_ee21_4887_bd76_18de3493c21a_0.fill(VALUES);
  }
  static final class NamesHolder_xgboost_03e1a270_ee21_4887_bd76_18de3493c21a_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "current_player_deadwood";
      sa[1] = "num_melds";
      sa[2] = "turns_taken";
    }
  }
}

class xgboost_03e1a270_ee21_4887_bd76_18de3493c21a_Tree_g_0_t_0 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 10.5f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 7.5f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 5.5f) ?
          0.14745913f
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 11.5f) ?
            0.14571713f
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 27.5f) ?
              0.13909273f
              :
              0.10000001f
            )
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 12.5f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 9.5f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.5f) ?
              0.14270186f
              :
              0.11785714f
            )
            :
            0.13406864f
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 21.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 8.5f) ?
              0.12683333f
              :
              0.115129456f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 28.5f) ?
              0.09013762f
              :
              -0.025000002f
            )
          )
        )
      )
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
        ((Double.isNaN(data[1]) || ((float)data[1]) < 0.5f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 4.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 1.5f) ?
              -0.02803794f
              :
              -0.04142474f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 7.5f) ?
              -0.053733267f
              :
              -0.067701176f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 5.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 3.5f) ?
              0.006914703f
              :
              -0.009198783f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 12.5f) ?
              0.025198098f
              :
              -0.024800671f
            )
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 7.5f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 16.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.5f) ?
              0.09344262f
              :
              0.061490968f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.5f) ?
              0.05421687f
              :
              0.028747818f
            )
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 15.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 12.5f) ?
              0.042383432f
              :
              0.020541325f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 11.5f) ?
              0.013928794f
              :
              -0.004421642f
            )
          )
        )
      )
    );
  }
}

class xgboost_03e1a270_ee21_4887_bd76_18de3493c21a_Tree_g_0_t_1 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 10.5f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 7.5f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 15.5f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 5.5f) ?
            0.10441877f
            :
            0.100800775f
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 2.5f) ?
            0.10292112f
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 16.5f) ?
              0.090533584f
              :
              0.09757746f
            )
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 12.5f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 6.5f) ?
            0.10292676f
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.5f) ?
              0.095741645f
              :
              0.04077881f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 19.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 8.5f) ?
              0.09064809f
              :
              0.08172059f
            )
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
              0.10382494f
              :
              0.062161613f
            )
          )
        )
      )
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
        ((Double.isNaN(data[1]) || ((float)data[1]) < 0.5f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 3.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 73.5f) ?
              -0.025190664f
              :
              -0.0027902317f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 52.5f) ?
              -0.045004863f
              :
              -0.032995872f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 7.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 1.5f) ?
              0.013602597f
              :
              -0.0048740874f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 16.5f) ?
              -0.0023677351f
              :
              -0.021961536f
            )
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 7.5f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 14.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 3.5f) ?
              0.08738402f
              :
              0.056167755f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 3.5f) ?
              0.04548369f
              :
              0.024636954f
            )
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 15.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 10.5f) ?
              0.034737777f
              :
              0.016580338f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 9.5f) ?
              0.01339185f
              :
              1.487067E-4f
            )
          )
        )
      )
    );
  }
}

class xgboost_03e1a270_ee21_4887_bd76_18de3493c21a_Tree_g_0_t_2 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 11.5f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 10.5f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 7.5f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 12.5f) ?
            0.07248062f
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 6.5f) ?
              0.070574135f
              :
              0.066042624f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 12.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 8.5f) ?
              0.07089349f
              :
              0.06578549f
            )
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
              0.07642958f
              :
              0.05597572f
            )
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 9.5f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 5.5f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
              -0.022287453f
              :
              0.06417145f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 6.5f) ?
              0.0497351f
              :
              0.04252326f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 16.5f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
              0.03945797f
              :
              0.023941021f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 21.5f) ?
              0.004965421f
              :
              0.02594424f
            )
          )
        )
      )
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
        ((Double.isNaN(data[1]) || ((float)data[1]) < 0.5f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 6.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 1.5f) ?
              -0.012373929f
              :
              -0.021656562f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 44.5f) ?
              -0.040086787f
              :
              -0.028277654f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 3.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 24.5f) ?
              0.02685717f
              :
              0.0034585588f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 10.5f) ?
              -0.007217085f
              :
              -0.018573165f
            )
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 5.5f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 19.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 2.5f) ?
              0.06034084f
              :
              0.039909683f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 1.5f) ?
              0.037621647f
              :
              0.012939257f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 9.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 17.5f) ?
              0.023061227f
              :
              0.0070731384f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 19.5f) ?
              0.0078045484f
              :
              -0.015254746f
            )
          )
        )
      )
    );
  }
}

class xgboost_03e1a270_ee21_4887_bd76_18de3493c21a_Tree_g_0_t_3 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 12.5f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 10.5f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 8.5f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 6.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 14.5f) ?
              0.051389147f
              :
              0.04864305f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 18.5f) ?
              0.048378307f
              :
              0.04105524f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 25.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 11.5f) ?
              0.048322808f
              :
              0.03869205f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 28.5f) ?
              -0.015710222f
              :
              -0.1334559f
            )
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 11.5f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 3.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 2.5f) ?
              0.06622877f
              :
              0.051689245f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 9.5f) ?
              0.028869474f
              :
              0.022020519f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 15.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 14.5f) ?
              0.016160006f
              :
              0.013069607f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 11.5f) ?
              0.0074553243f
              :
              -0.0025929578f
            )
          )
        )
      )
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
        ((Double.isNaN(data[1]) || ((float)data[1]) < 0.5f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 3.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 69.5f) ?
              -0.012650455f
              :
              -0.0018685091f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 8.5f) ?
              -0.018212033f
              :
              -0.025855161f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 5.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 1.5f) ?
              0.008308782f
              :
              -0.0011668887f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 12.5f) ?
              -0.0068454677f
              :
              -0.015866468f
            )
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 6.5f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 20.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 3.5f) ?
              0.035275504f
              :
              0.021303616f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 1.5f) ?
              0.02234817f
              :
              0.0068192044f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 21.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 16.5f) ?
              0.008810053f
              :
              0.0013995058f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 23.5f) ?
              -0.01942883f
              :
              -0.055823356f
            )
          )
        )
      )
    );
  }
}

class xgboost_03e1a270_ee21_4887_bd76_18de3493c21a_Tree_g_0_t_4 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 14.5f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 10.5f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 9.5f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 11.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 6.5f) ?
              0.0368448f
              :
              0.03489003f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 8.5f) ?
              0.033596992f
              :
              0.028554916f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 19.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 8.5f) ?
              0.034670874f
              :
              0.027343784f
            )
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
              0.05237542f
              :
              -0.004786764f
            )
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 9.5f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 5.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 2.5f) ?
              0.040666822f
              :
              0.026965754f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 11.5f) ?
              0.0219861f
              :
              0.015516488f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 16.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 12.5f) ?
              0.011940975f
              :
              0.0072143003f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 13.5f) ?
              0.0010375502f
              :
              -0.016166136f
            )
          )
        )
      )
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
        ((Double.isNaN(data[1]) || ((float)data[1]) < 0.5f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 52.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 1.5f) ?
              -0.005177384f
              :
              -0.015765462f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 63.5f) ?
              -0.010189374f
              :
              -0.004532598f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 9.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 17.5f) ?
              0.025009582f
              :
              -0.0016217213f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 16.5f) ?
              -0.008385236f
              :
              -0.017685283f
            )
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 4.5f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 18.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 1.5f) ?
              0.038348053f
              :
              0.024277184f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 1.5f) ?
              0.019058643f
              :
              0.0075766165f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 8.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 19.5f) ?
              0.009561384f
              :
              0.0024180992f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 18.5f) ?
              -2.822695E-5f
              :
              -0.016502934f
            )
          )
        )
      )
    );
  }
}

class xgboost_03e1a270_ee21_4887_bd76_18de3493c21a_Tree_g_0_t_5 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 16.5f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 10.5f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 18.5f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 9.5f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
              0.032487094f
              :
              0.024087591f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 8.5f) ?
              0.024281576f
              :
              0.019411653f
            )
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 8.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 28.5f) ?
              0.021459525f
              :
              0.04626036f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 27.5f) ?
              0.011572161f
              :
              -0.07490459f
            )
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 8.5f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 3.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 12.5f) ?
              0.030598477f
              :
              0.021025691f
            )
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
              0.022298884f
              :
              0.012581161f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 14.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 12.5f) ?
              0.010347286f
              :
              0.0052875765f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 24.5f) ?
              1.3488332E-4f
              :
              -0.02539494f
            )
          )
        )
      )
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 3.5f) ?
          ((Double.isNaN(data[1]) || ((float)data[1]) < 0.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 38.5f) ?
              -0.048784155f
              :
              -0.005174449f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 25.5f) ?
              0.016026156f
              :
              0.002153135f
            )
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 32.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 9.5f) ?
              -0.0011251488f
              :
              -0.007035782f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 8.5f) ?
              -0.0070603574f
              :
              -0.012745806f
            )
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 9.5f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 1.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 25.5f) ?
              0.024177883f
              :
              -0.0036095844f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 19.5f) ?
              0.008717663f
              :
              0.0024726384f
            )
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 23.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 18.5f) ?
              -0.008717292f
              :
              0.0051699174f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 13.5f) ?
              -0.012888843f
              :
              -0.07380366f
            )
          )
        )
      )
    );
  }
}

class xgboost_03e1a270_ee21_4887_bd76_18de3493c21a_Tree_g_0_t_6 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 16.5f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 10.5f) ?
        ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 15.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 13.5f) ?
              0.022549966f
              :
              0.014219141f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 9.5f) ?
              0.024541711f
              :
              0.040016554f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 15.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 5.5f) ?
              0.018494692f
              :
              0.016096856f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 9.5f) ?
              0.015020911f
              :
              0.0036235186f
            )
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 6.5f) ?
          ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.5f) ?
              0.0133359f
              :
              0.058504682f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 1.5f) ?
              0.021747617f
              :
              0.011842068f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 14.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 12.5f) ?
              0.007745097f
              :
              0.0042054704f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 25.5f) ?
              -4.553796E-5f
              :
              -0.023655465f
            )
          )
        )
      )
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 5.5f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 24.5f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 1.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 23.5f) ?
              0.016197022f
              :
              0.045121662f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 20.5f) ?
              0.009988266f
              :
              0.0037684413f
            )
          )
          :
          ((Double.isNaN(data[1]) || ((float)data[1]) < 0.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 69.5f) ?
              -0.0049905973f
              :
              0.0024510343f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 57.5f) ?
              1.4312788E-4f
              :
              0.026838478f
            )
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 18.5f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 26.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 7.5f) ?
              0.0011071707f
              :
              -0.0023636268f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 14.5f) ?
              -0.005253813f
              :
              -0.017889602f
            )
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 29.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 23.5f) ?
              -0.0132521475f
              :
              -0.036616385f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 44.5f) ?
              0.010985721f
              :
              0.07002941f
            )
          )
        )
      )
    );
  }
}

class xgboost_03e1a270_ee21_4887_bd76_18de3493c21a_Tree_g_0_t_7 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 14.5f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 10.5f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 6.5f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 2.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 17.5f) ?
              0.013158754f
              :
              0.016493607f
            )
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 2.5f) ?
              0.0131223425f
              :
              0.01063433f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 18.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 8.5f) ?
              0.01292748f
              :
              0.010333113f
            )
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
              0.020774785f
              :
              0.004000713f
            )
          )
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 7.5f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 5.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.5f) ?
              0.0094896685f
              :
              0.0134284645f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 11.5f) ?
              0.010713126f
              :
              0.0067611793f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 16.5f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
              0.0076303883f
              :
              0.0034922983f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 13.5f) ?
              0.001381614f
              :
              -0.01094555f
            )
          )
        )
      )
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 1.5f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 25.5f) ?
          ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 20.5f) ?
              0.0030070292f
              :
              0.027737716f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 20.5f) ?
              0.015156372f
              :
              0.009169498f
            )
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 27.5f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
              -0.0075883106f
              :
              -0.01834884f
            )
            :
            ((Double.isNaN(data[1]) || ((float)data[1]) < 0.5f) ?
              -1.262876E-4f
              :
              0.0049379035f
            )
          )
        )
        :
        ((Double.isNaN(data[1]) || ((float)data[1]) < 0.5f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 84.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 68.5f) ?
              -0.005602723f
              :
              9.0485637E-4f
            )
            :
            0.13300677f
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 13.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 19.5f) ?
              0.003046373f
              :
              -0.001198385f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 23.5f) ?
              -0.0030074369f
              :
              -0.0111138f
            )
          )
        )
      )
    );
  }
}

class xgboost_03e1a270_ee21_4887_bd76_18de3493c21a_Tree_g_0_t_8 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 11.5f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 9.5f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 31.5f) ?
          ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 27.0f) ?
              0.013855171f
              :
              -0.050729766f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 9.5f) ?
              0.009234646f
              :
              0.0076818517f
            )
          )
          :
          -0.06485301f
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 26.5f) ?
          ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 19.5f) ?
              0.01027458f
              :
              0.037636686f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.5f) ?
              0.01157254f
              :
              0.0044890568f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 30.0f) ?
            ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
              0.03105838f
              :
              -0.05666798f
            )
            :
            0.0714165f
          )
        )
      )
      :
      ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 1.5f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 24.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 23.5f) ?
              0.012509064f
              :
              0.034427334f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 48.5f) ?
              0.0035439949f
              :
              -1.3288582E-5f
            )
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 32.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 5.5f) ?
              0.0028563968f
              :
              -0.0015220927f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 6.5f) ?
              -0.0019495459f
              :
              -0.0050903154f
            )
          )
        )
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 28.5f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 25.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 4.5f) ?
              0.005979061f
              :
              0.0010880873f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 12.5f) ?
              -0.0057213902f
              :
              -0.071585365f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 10.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 1.5f) ?
              0.0019218079f
              :
              0.01596136f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 30.5f) ?
              0.005934978f
              :
              -0.08436096f
            )
          )
        )
      )
    );
  }
}

class xgboost_03e1a270_ee21_4887_bd76_18de3493c21a_Tree_g_0_t_9 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 15.5f) ?
      ((Double.isNaN(data[0]) || ((float)data[0]) < 10.5f) ?
        ((Double.isNaN(data[2]) || ((float)data[2]) < 31.5f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 18.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 17.5f) ?
              0.0056669754f
              :
              0.009141667f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 9.5f) ?
              0.0048871497f
              :
              -0.004912264f
            )
          )
          :
          -0.055125058f
        )
        :
        ((Double.isNaN(data[2]) || ((float)data[2]) < 19.5f) ?
          ((Double.isNaN(data[1]) || ((float)data[1]) < 1.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 3.5f) ?
              0.0414998f
              :
              0.0069748866f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 10.5f) ?
              0.0034733708f
              :
              5.547601E-4f
            )
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 12.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 21.5f) ?
              -0.0019116957f
              :
              0.012825266f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 23.5f) ?
              -0.0060880072f
              :
              -0.03433557f
            )
          )
        )
      )
      :
      ((Double.isNaN(data[2]) || ((float)data[2]) < 11.5f) ?
        ((Double.isNaN(data[0]) || ((float)data[0]) < 26.5f) ?
          ((Double.isNaN(data[2]) || ((float)data[2]) < 5.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 18.5f) ?
              0.007480258f
              :
              0.0029588114f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 24.5f) ?
              -6.883961E-4f
              :
              0.0038794728f
            )
          )
          :
          ((Double.isNaN(data[2]) || ((float)data[2]) < 2.5f) ?
            ((Double.isNaN(data[0]) || ((float)data[0]) < 46.5f) ?
              0.002740559f
              :
              -9.189237E-4f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 33.5f) ?
              -3.6522458E-4f
              :
              -0.0024776089f
            )
          )
        )
        :
        ((Double.isNaN(data[0]) || ((float)data[0]) < 38.5f) ?
          ((Double.isNaN(data[0]) || ((float)data[0]) < 37.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 16.5f) ?
              -0.0024788054f
              :
              -0.0063481033f
            )
            :
            ((Double.isNaN(data[2]) || ((float)data[2]) < 12.5f) ?
              0.06671837f
              :
              0.011554213f
            )
          )
          :
          ((Double.isNaN(data[0]) || ((float)data[0]) < 43.5f) ?
            ((Double.isNaN(data[2]) || ((float)data[2]) < 19.5f) ?
              -0.0163496f
              :
              -0.07035203f
            )
            :
            ((Double.isNaN(data[0]) || ((float)data[0]) < 46.5f) ?
              0.008710609f
              :
              -0.01024057f
            )
          )
        )
      )
    );
  }
}

